let
    Source = xer,
    #"Filtered Rows" = Table.SelectRows(Source, each ([#"Table "] = "TASK") and ([Column1] <> "%T")),
    #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows"),
    #"Appended Query" = Table.Combine({#"Promoted Headers", Task_Schema}),
    #"Removed Other Columns" = Table.SelectColumns(#"Appended Query",{"task_id", "proj_id", "wbs_id", "clndr_id", "phys_complete_pct", "rev_fdbk_flag", "lock_plan_flag", "auto_compute_act_flag", "complete_pct_type", "task_type", "duration_type", "status_code", "task_code", "task_name", "rsrc_id", "total_float_hr_cnt", "free_float_hr_cnt", "remain_drtn_hr_cnt", "act_work_qty", "remain_work_qty", "target_work_qty", "target_drtn_hr_cnt", "target_equip_qty", "act_equip_qty", "remain_equip_qty", "cstr_date", "act_start_date", "act_end_date", "late_start_date", "late_end_date", "expect_end_date", "early_start_date", "early_end_date", "restart_date", "reend_date", "target_start_date", "target_end_date", "rem_late_start_date", "rem_late_end_date", "cstr_type", "priority_type", "suspend_date", "resume_date", "float_path", "float_path_order", "guid", "tmpl_guid", "cstr_date2", "cstr_type2", "driving_path_flag", "act_this_per_work_qty", "act_this_per_equip_qty", "external_early_start_date", "external_late_end_date", "create_date", "update_date", "create_user", "update_user"}),
    Task_ID_Key = Table.AddColumn(#"Removed Other Columns", "Task_ID_Key", each [proj_id]&"."&[task_id]),
    #"Changed Type" = Table.TransformColumnTypes(Task_ID_Key,{{"Task_ID_Key", type text}}),
    wbs_id_Key = Table.AddColumn(#"Changed Type", "wbs_id_Key", each [proj_id]&"."&[wbs_id]),
    clndr_id.Key = Table.AddColumn(wbs_id_Key, "clndr_id.Key", each [proj_id]&"."&[clndr_id]),
    #"Changed Type1" = Table.TransformColumnTypes(clndr_id.Key,{{"wbs_id_Key", type text}, {"clndr_id.Key", type text}}),
    #"Filtered Rows1" = Table.SelectRows(#"Changed Type1", each ([task_id] <> "task_id")),
    #"Changed Type2" = Table.TransformColumnTypes(#"Filtered Rows1",{{"total_float_hr_cnt", type number}, {"free_float_hr_cnt", type number}, {"remain_drtn_hr_cnt", type number}, {"act_work_qty", type number}, {"remain_work_qty", type number}, {"target_work_qty", type number}, {"target_drtn_hr_cnt", type number}, {"target_equip_qty", type number}, {"act_equip_qty", type number}, {"remain_equip_qty", type number}, {"cstr_date", type datetime}, {"act_start_date", type datetime}, {"act_end_date", type datetime}, {"late_start_date", type datetime}, {"late_end_date", type datetime}, {"expect_end_date", type datetime}, {"early_start_date", type datetime}, {"early_end_date", type datetime}, {"restart_date", type datetime}, {"reend_date", type datetime}, {"target_start_date", type datetime}, {"target_end_date", type datetime}, {"rem_late_start_date", type datetime}, {"rem_late_end_date", type datetime}, {"phys_complete_pct", type number}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Changed Type2",{{"cstr_date", type date}, {"act_start_date", type date}, {"act_end_date", type date}, {"late_start_date", type date}, {"late_end_date", type date}, {"expect_end_date", type date}, {"early_start_date", type date}, {"early_end_date", type date}, {"restart_date", type date}, {"reend_date", type date}, {"target_start_date", type date}, {"target_end_date", type date}, {"rem_late_start_date", type date}, {"rem_late_end_date", type date}})
in
    #"Changed Type3"
